version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/.github/workflows" # Location of package manifests
    schedule:
      interval: "daily"
      versioning-strategy: increase-if-necessary
