name: AutoClone

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  
  schedule:
    - cron:  '*/1 * * * *'
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  Builds:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
     matrix:
      os: [ubuntu-latest, ubuntu-latest, ubuntu-latest, ubuntu-latest, ubuntu-latest, ubuntu-latest, ubuntu-latest, ubuntu-latest, ubuntu-latest, ubuntu-latest, ubuntu-latest, ubuntu-latest, ubuntu-latest, ubuntu-latest, ubuntu-latest, ubuntu-latest, ubuntu-latest, ubuntu-latest, ubuntu-latest, ubuntu-latest]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Find author
      run: echo "Authors is ${{ github.actor }}"
    - name: Clone1
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: Altify-Developing
        repository: Altify-Developing-Main
    - name: delete1
      run: |
         rm -r "Altify-Developing-Main"
    - name: Clone2
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: Altify-Developing
        repository: Altify-Developing-Main
    - name: delete3
      run: |
         rm -r "Altify-Developing-Main"
    - name: Clone3
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: Altify-Developing
        repository: Altify-Developing-Main
    - name: delete3
      run: |
         rm -r "Altify-Developing-Main"
    - name: Clone4
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: Altify-Developing
        repository: Altify-Developing-Main
    - name: delete4
      run: |
         rm -r "Altify-Developing-Main"
    - name: Clone5
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: Altify-Developing
        repository: Altify-Developing-Main
    - name: delete5
      run: |
         rm -r "Altify-Developing-Main"
  SendEmail1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: CINotify Email
      uses: cinotify/github-action@v1.1.0
      with:
        to: 'admin@psnator.com'
        subject: 'CloneBot'
        body: 'The bot is 100% completed'
