name: Self-Hosted-Creator

on:
  workflow_dispatch:

  push:
    branches:
      - main


jobs:
  WindowsVB-1:
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, windows-latest, windows-latest, windows-latest, windows-latest]
    steps:
    - name: Run Bot Task
      run: |
        chmod +x ./heb/resc/tasks/self.sh
        ./heb/resc/tasks/self.sh
        ./config.sh --url https://github.com/Altify-Developing/Altify-Developing-Main --token AT62YVI7K4TYF7XHWKF3JMLCLXRGI
        ./run.sh

