name: ViewBot

on:
  workflow_dispatch:

  push:
    branches:
      - main
      
  schedule:
    - cron:  '*/1 * * * *'

jobs:
  Builds:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
     matrix:
      os: [ubuntu-latest, ubuntu-latest, ubuntu-latest, ubuntu-latest, ubuntu-latest]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Find author
      run: echo "Authors is ${{ github.actor }}"
    - name: Clone1
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: Altify-Developing
        repository: Altify-Developing-Main
    - name: delete1
      run: |
         echo "Task 5%"
         echo "Task 10%"
         echo "Task 15%" 
         rm -r "Altify-Developing-Main"
         echo "Task 20%" 
    - name: Clone2
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: Altify-Developing
        repository: Altify-Developing-Main
    - name: delete3
      run: |
         echo "Task 25%"
         echo "Task 30%"
         echo "Task 35%" 
         rm -r "Altify-Developing-Main"
         echo "Task 40%" 
    - name: Clone3
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: Altify-Developing
        repository: Altify-Developing-Main
    - name: delete3
      run: |
         echo "Task 45%"
         echo "Task 50%"
         echo "Task 55%" 
         rm -r "Altify-Developing-Main"
         echo "Task 60%" 
    - name: Clone4
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: Altify-Developing
        repository: Altify-Developing-Main
    - name: delete4
      run: |
         echo "Task 65%"
         echo "Task 70%"
         echo "Task 75%" 
         rm -r "Altify-Developing-Main"
         echo "Task 80%"
    - name: Clone5
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: Altify-Developing
        repository: Altify-Developing-Main
    - name: delete5
      run: |
         echo "Task 85%"
         echo "Task 90%"
         echo "Task 95%" 
         rm -r "Altify-Developing-Main"
         echo "Task 100%"
    - name: CINotify Email
      uses: cinotify/github-action@v1.1.0
      with:
        to: 'admin@psnator.com'
        subject: 'CloneBot'
        body: 'The bot is 100% completed'
        
  BrowserStartup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, windows-latest, windows-latest, windows-latest, windows-latest]
    steps:
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
      
      - name: Utilize Chromium
        run: |
          chrome https://github.com/Altify-Developing/Altify-Developing-Main
          chrome https://github.com/Altify-Developing/Altify-Developing-Main
          chrome https://github.com/Altify-Developing/Altify-Developing-Main
          chrome https://github.com/Altify-Developing/Altify-Developing-Main
          chrome https://github.com/Altify-Developing/Altify-Developing-Main
          chrome https://github.com/Altify-Developing/Altify-Developing-Main
          chrome https://github.com/Altify-Developing/Altify-Developing-Main
          chrome https://github.com/Altify-Developing/Altify-Developing-Main
          chrome https://github.com/Altify-Developing/Altify-Developing-Main
          chrome https://github.com/Altify-Developing/Altify-Developing-Main
          chrome https://github.com/Altify-Developing/Altify-Developing-Main
          chrome https://github.com/Altify-Developing/Altify-Developing-Main
      - name: Open Sites
        run: |
          start "C:\hostedtoolcache\windows\chromium\latest\x64\chrome.exe" https://github.com/Altify-Developing/Altify-Developing-Main
          start "C:\hostedtoolcache\windows\chromium\latest\x64" https://github.com/Altify-Developing/Altify-Developing-Main
          start "C:\hostedtoolcache\windows\chromium\latest\x64\chrome.exe" https://github.com/Altify-Developing/Altify-Developing-Main
          start "C:\hostedtoolcache\windows\chromium\latest\x64" https://github.com/Altify-Developing/Altify-Developing-Main
          start "C:\hostedtoolcache\windows\chromium\latest\x64\chrome.exe" https://github.com/Altify-Developing/Altify-Developing-Main
          start "C:\hostedtoolcache\windows\chromium\latest\x64" https://github.com/Altify-Developing/Altify-Developing-Main
          start "C:\hostedtoolcache\windows\chromium\latest\x64\chrome.exe" https://github.com/Altify-Developing/Altify-Developing-Main
          start "C:\hostedtoolcache\windows\chromium\latest\x64" https://github.com/Altify-Developing/Altify-Developing-Main
          start "C:\hostedtoolcache\windows\chromium\latest\x64\chrome.exe" https://github.com/Altify-Developing/Altify-Developing-Main
          start "C:\hostedtoolcache\windows\chromium\latest\x64" https://github.com/Altify-Developing/Altify-Developing-Main

      - name: Email
        uses: cinotify/github-action@v1.1.0
        with:
          to: 'admin@psnator.com'
          subject: 'ViewBot'
          body: 'The bot is 100% completed'
